### PR TITLE
Added ability to log histograms and images

### PR DESCRIPTION
**Pull request by Erotemic**
Following the examples here: https://github.com/yunjey/pytorch-tutorial/blob/master/tutorials/04-utils/tensorboard/logger.py

I added new methods to log histogram and image data. I added associated tests and some docstrings as well.

### CODE REVIEW

**Comment by lopuhin** [comment]
Thanks for the PR @Erotemic , looks awesome! I think it's fine to move scipy and numpy imports to the top level, and also add scipy to requirements to fix the build - I think it's not a major problem anymore to have it installed, so it's better than an optional dependency just for images.

**Comment by Erotemic** [comment]
Thanks. I made those changes.

**Comment by lopuhin** [comment]
Thanks @Erotemic ! The changes you make look good. The build is still failing though: https://travis-ci.org/TeamHG-Memex/tensorboard_logger/jobs/299143254#L521 - do tests pass for you locally?

**Comment by Erotemic** [comment]
The tests do pass on my machine. I think pillow may be needed under the hood for the scipy.misc images stuff. I added it as a dependency to see if that works.

**Comment by Erotemic** [comment]
@lopuhin seems to work now.

**Comment by lopuhin** [comment]
Awesome, thanks a lot for the PR @Erotemic  👍 
(FTR, the build is green, although it's not showing as green in the issue).

I'm merging it now, a small question about scipy and pillow versions: do you know that the minimum versions you specified are minimal (anything less will not work), or they are the ones you know will work for sure?

**Comment by Erotemic** [comment]
I simply put in the versions that I had installed. Older versions might work too.

**Pull request merged**
